workflows:
  android-build:
    name: Build Android APK
    instance_type: mac_mini_m1
    environment:
      android_sdk_version: "34"
      java_version: "17"
    scripts:
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
