workflows:
  android-build:
    name: Build Android APK
    instance_type: mac_mini_m1
    environment:
      groups:
        - android-sdk
    scripts:
      - name: Grant execute permission for gradlew
        script: | 
          chmod +x ./gradlew
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
