workflows:
  android-build:
    name: Build Android APK
    instance_type: mac_mini_m1
    environment:
      groups:
        - android-sdk # هذه هي الطريقة الصحيحة لتضمين أدوات أندرويد
    scripts:
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
